debug: true
timezone: "Europe/Kiev"
locale: ua

mongo:
    default:
      server: 'mongodb://localhost:27017'
      db: 'cryo'

modules:
    exclude: []
    paths: ["app/modules"]

twig:
    paths: ["app/views", "app/modules"]